"""
Model training utility for IDPS
"""
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path
from config.settings import LOGIN_ATTEMPTS_LOG
from src.core.ml_model import intrusion_model
from src.core.logger import get_logger

logger = get_logger(__name__)

def generate_sample_data():
    """Generate sample training data if no real data exists"""
    logger.info("Generating sample training data...")
    
    # Create sample data with both normal and attack patterns
    sample_data = []
    
    # Normal login patterns (legitimate users)
    normal_usernames = ["john.doe", "jane.smith", "alice.brown", "bob.wilson", "carol.jones"]
    normal_passwords = ["SecurePass123!", "MyPassword2023", "CompanyPass456", "UserLogin789"]
    normal_ips = ["192.168.1.10", "192.168.1.15", "192.168.1.20"]
    
    # Attack patterns (brute force, common passwords)
    attack_usernames = ["admin", "root", "administrator", "test", "user", "guest"]
    attack_passwords = ["123", "password", "admin", "test", "123456", "pass", ""]
    attack_ips = ["10.0.0.5", "172.16.0.10", "192.168.100.50"]
    
    base_time = datetime.now() - timedelta(days=7)
    
    # Generate normal login attempts (70% of data)
    for i in range(700):
        timestamp = base_time + timedelta(
            minutes=np.random.randint(0, 7*24*60)  # Random time in last 7 days
        )
        sample_data.append({
            "ip": np.random.choice(normal_ips),
            "username": np.random.choice(normal_usernames),
            "password": np.random.choice(normal_passwords),
            "timestamp": timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            "label": 0  # Normal
        })
    
    # Generate attack attempts (30% of data)
    for i in range(300):
        timestamp = base_time + timedelta(
            minutes=np.random.randint(0, 7*24*60)
        )
        sample_data.append({
            "ip": np.random.choice(attack_ips),
            "username": np.random.choice(attack_usernames),
            "password": np.random.choice(attack_passwords),
            "timestamp": timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            "label": 1  # Attack
        })
    
    # Save sample data to the log file
    df = pd.DataFrame(sample_data)
    df = df.sample(frac=1).reset_index(drop=True)  # Shuffle the data
    
    # Save without the label column (labels will be generated by the model)
    df[['ip', 'username', 'password', 'timestamp']].to_csv(
        LOGIN_ATTEMPTS_LOG, 
        index=False, 
        header=False
    )
    
    logger.info(f"Generated {len(sample_data)} sample login attempts")
    return True

def train_model():
    """Train the intrusion detection model"""
    logger.info("Starting model training...")
    
    try:
        # Check if training data exists
        if not LOGIN_ATTEMPTS_LOG.exists() or LOGIN_ATTEMPTS_LOG.stat().st_size == 0:
            logger.warning("No training data found. Generating sample data...")
            generate_sample_data()
        
        # Train the model
        success = intrusion_model.train()
        
        if success:
            logger.info("✅ Model training completed successfully!")
            
            # Display model information
            model_info = intrusion_model.model_info()
            logger.info("📊 Model Information:")
            for key, value in model_info.items():
                logger.info(f"  {key}: {value}")
            
            return True
        else:
            logger.error("❌ Model training failed!")
            return False
            
    except Exception as e:
        logger.error(f"Error during model training: {e}")
        return False

def retrain_model():
    """Retrain the model with new data"""
    logger.info("Retraining model with updated data...")
    return train_model()

def validate_model():
    """Validate the trained model"""
    logger.info("Validating model...")
    
    if not intrusion_model.is_trained:
        logger.error("Model is not trained. Please train the model first.")
        return False
    
    try:
        # Test with some sample inputs
        test_cases = [
            # Normal cases
            ("john.doe", "SecurePassword123", True),
            ("alice.brown", "MyCompanyPass456", True),
            
            # Attack cases
            ("admin", "123", False),
            ("root", "password", False),
            ("test", "", False),
        ]
        
        logger.info("Testing model with sample inputs:")
        
        for username, password, expected_normal in test_cases:
            prediction = intrusion_model.predict(username, password)
            result = "NORMAL" if prediction == 0 else "ATTACK"
            expected = "NORMAL" if expected_normal else "ATTACK"
            
            status = "✅" if (prediction == 0) == expected_normal else "❌"
            logger.info(f"  {status} {username}:{password} → {result} (expected: {expected})")
        
        return True
        
    except Exception as e:
        logger.error(f"Error validating model: {e}")
        return False

def main():
    """Main function for training script"""
    logger.info("🤖 IDPS Model Training Utility")
    logger.info("=" * 50)
    
    # Train the model
    if train_model():
        # Validate the model
        validate_model()
        logger.info("\n✅ Training process completed successfully!")
        logger.info("The model is now ready for use in the IDS monitor.")
    else:
        logger.error("\n❌ Training process failed!")
        return 1
    
    return 0

if __name__ == "__main__":
    import sys
    sys.exit(main())
